### ISSUE TITLE
Timed out waiting for friends count to load

### ISSUE THREAD

**Issue by jayjupdhig** [narkopolo/fb_friend_list_scraper#5]
![image](https://user-images.githubusercontent.com/42765391/185891148-da697c92-d95b-4e53-a5d1-dc79e50ddc5a.png)

- Is it not able to read friends from a private profile?
AND/OR
- Do i need to install some firefox plugins?

**Comment by jayjupdhig** [comment]
I saw that my fb username was not correct with letters (capital ones)

Now is all correct but i get that:

`
    ______    ____     _                _____      __
   / __/ /_  / __/____(_)__  ____  ____/ / (_)____/ /____________________  ____  ___  _____
  / /_/ __ \/ /_/ ___/ / _ \/ __ \/ __  / / / ___/ __/ ___/ ___/ ___/ __ `/ __ \/ _ \/ ___/
 / __/ /_/ / __/ /  / /  __/ / / / /_/ / / (__  ) /_(__  ) /__/ /  / /_/ / /_/ /  __/ /
/_/ /_.___/_/ /_/  /_/\___/_/ /_/\__,_/_/_/____/\__/____/\___/_/   \__,_/ .___/\___/_/
(banners are cool, shut up)                                     v0.3.6 /_/ by narkopolo

[+] Starting webdriver
[+] Requesting login page
[+] Non-english detected. Changing language to English (UK)
Traceback (most recent call last):
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\fb_friend_list_scraper\scraper.py", line 140, in login
    cookie_btn = driver.find_element(By.XPATH, '//*[@value="Only Allow Essential Cookies"]')
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //*[@value="Only Allow Essential Cookies"]
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:188:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:400:5
element.find/</<@chrome://remote/content/marionette/element.js:292:16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\Scripts\fbfriendlistscraper.exe\__main__.py", line 7, in <module>
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\fb_friend_list_scraper\scraper.py", line 382, in main
    do_scrape(driver, email, password, user_to_scrape, outfile_path, args)
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\fb_friend_list_scraper\scraper.py", line 291, in do_scrape
    login(driver, email, password)
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\fb_friend_list_scraper\scraper.py", line 144, in login
    cookie_btn.click()
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "D:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <button id="u_0_l_yn" class="_54k8 _52jh _56bs _a6as _56bt" type="submit"> could not be scrolled into view
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:188:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.jsm:298:5
webdriverClickElement@chrome://remote/content/marionette/interaction.js:156:11
interaction.clickElement@chrome://remote/content/marionette/interaction.js:125:11
clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:205:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:93:31


C:\Users\user1>
`


Why?

**Comment by n0kovo** [comment]
No, the script is not able to see friend lists that you are not. Your second error seems to be a failure to find the cookie banner, which is something I'll look into.

**Comment by kosuodhmwa** [comment]
**_"No, the script is not able to see friend lists that you are not."_**

So i can only view the friends list of my own profile... i was thinking about to create a FB friends statistics tool for every one - at least if they are public for "FB friends statistics tool"-account i would creat eif it would work. But i doesn't.

But, i think, in theory that is not impossible? (In user interaction mode, normal way via browser wih a human, i can also see the [some] friends lists of some FB friends... not a, but that's their privacy setting...;-)) 

**_"Your second error seems to be a failure to find the cookie banner, which is something I'll look into."_**

That's very nice, thank you very very much!! :-)

**Comment by n0kovo** [comment]
If someone has hidden their friend list via the privacy settings, then of course you can't scrape it since it's, you know, hidden. This tool is for scraping public friend lists.

**Comment by kosuodhmwa** [comment]
Thank you very much for your fast feedback!! :-)
