### ISSUE TITLE
AttributeError module Openssl ssl has no attribute 'SSLv2_METHOD

### ISSUE THREAD

**Issue by ghost** [narkopolo/fb_friend_list_scraper#8]
How to fix x this error 

fbfriendlistscraper
Traceback (most recent call last):
  File "/home/kali/venv/bin/fbfriendlistscraper", line 5, in <module>
    from fb_friend_list_scraper.scraper import main
  File "/home/kali/venv/lib/python3.11/site-packages/fb_friend_list_scraper/scraper.py", line 32, in <module>
    from seleniumwire import webdriver
  File "/home/kali/venv/lib/python3.11/site-packages/seleniumwire/webdriver.py", line 27, in <module>
    from seleniumwire import backend, utils
  File "/home/kali/venv/lib/python3.11/site-packages/seleniumwire/backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "/home/kali/venv/lib/python3.11/site-packages/seleniumwire/server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "/home/kali/venv/lib/python3.11/site-packages/seleniumwire/handler.py", line 5, in <module>
    from seleniumwire import har
  File "/home/kali/venv/lib/python3.11/site-packages/seleniumwire/har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "/home/kali/venv/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "/home/kali/venv/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 44, in <module>
    "SSLv3": (SSL.SSLv3_METHOD, BASIC_OPTIONS),
              ^^^^^^^^^^^^^^^^
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'. Did you mean: 'SSLv23_METHOD'?

**Comment by n0kovo** [comment]
See https://github.com/n0kovo/fb_friend_list_scraper/issues/6
